[package]
name = "dumbchess-rs"
version = "0.1.0"
authors = ["fdemian <federicodamiancaminiti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"
regex = "1"
